### ISSUE TITLE
HTML_DEFAULT_TRACKER and HTML_SITE_NAME are ignored

### ISSUE THREAD

**Issue by Freekers** [Thom-x/docker-fr24feed-piaware-dump1090#59]
## Specifications

  - Image hash or version: latest
  - Platform: linux
  - Subsystem: arm/v6

## Expected Behavior
`HTML_DEFAULT_TRACKER` if set to Flightradar24 will change the default tracker in the UI to FlightRadar 24.
`HTML_SITE_NAME` if set will change the default site title from 'Dump1090 plane tracker' to the set value

## Actual Behavior
`HTML_DEFAULT_TRACKER` and `HTML_SITE_NAME` are ignored and fall back to defaults.

## Steps to Reproduce the Problem
  1. Spin up Docker container using the following docker-compose file:
```
version: "3.7"
services:
  fr24feed-piaware:
    image: "thomx/fr24feed-piaware"
    container_name: piaware
    restart: unless-stopped
    environment: 
      - "FR24FEED_FR24KEY=XXXXXXXXX"
      - "PIAWARE_FEEDER_DASH_ID=XXXXXXXXXX"
      - "HTML_SITE_LAT=XXXXXXXX"
      - "HTML_SITE_LON=XXXXXXX"
      - "HTML_SITE_NAME=MyAwesomeFlightRadar"
      - "HTML_DEFAULT_TRACKER=Flightradar24"
      - "HTML_RECEIVER_STATS_PAGE_FLIGHTAWARE=https://flightaware.com/adsb/stats/user/XXXXXXX"
      - "HTML_RECEIVER_STATS_PAGE_FLIGHTRADAR24=https://www.flightradar24.com/account/feed-stats/?id=XXXXXXXX"
      - "HTML_FR24_FEEDER_STATUS_PAGE=http://192.168.30.222:8754/"
    devices:
      - "/dev/bus/usb"
    ports:
      - "8754:8754"
      - "8082:8080"
```
