### ISSUE TITLE
Config Remote Dump1090 for Planefinder 

### ISSUE THREAD

**Issue by steffenxx** [Thom-x/docker-fr24feed-piaware-dump1090#96]
I use the current version of Dump1090-fa without piaware client on a Pi Zero. It provides the receiver's data on the LAN via BEAST on port 30005. I use the Thom-X container as a client. In the stack, the remote IP of the DUMP1090 can be configured for FR24Feed and Piaware. These clients are working well. I cannot find any environment variables for Planefinder (e.g. tcp_address etc.). You can configure the connection type, IP etc. via the config page "dockerhost:30053" but this only works as long as the container is running. I have saved the config file /planefinder/config/pfclient-config.json via volume mapping on the Dockerhost and it is also available to the container after the restart, but unfortunately it is not used by the PFCLIENT.

How can I configure a remote Dump1090 in Planefinder?

Here is my complete Stack:

`version: "2"
services:

  fr24feed-piaware:
    container_name: fr24feed
    networks:
      net:
        ipv4_address: xx.xx.xx.xx
    dns: 
       - xx.xx.xx.xx
    hostname: fr24feed
    image: thomx/fr24feed-piaware:latest
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro # needed to sync time for MLAT
       - /home/pi/nfs/planefinder/config:/planefinder/config/
       - /home/pi/nfs/planefinder/log:/planefinder/log/
    environment:
####### Allgemeine Einstellung ############## 
       - HTML_DEFAULT_TRACKER=FlightAware
       - SERVICE_ENABLE_DUMP1090=false
       - SERVICE_ENABLE_HTTP=true
       - HTML_SITE_LAT=xxxxx
       - HTML_SITE_LON=xxxxx
       - HTML_SITE_NAME=xxxx
       
####### FlightAware Einstellung ############## 
       - SERVICE_ENABLE_PIAWARE=true
       - PIAWARE_FEEDER_DASH_ID=xxxxxxxxx
       - PIAWARE_RECEIVER_DASH_TYPE=other
       - PIAWARE_RECEIVER_DASH_HOST=xx.xx.xx.xx
       - PIAWARE_RECEIVER_DASH_PORT=30005
       - HTML_RECEIVER_STATS_PAGE_FLIGHTAWARE=https://flightaware.com/adsb/stats/user/

####### FlightRadar24 Einstellung ##############        
       - SERVICE_ENABLE_FR24FEED=true
       - FR24FEED_FR24KEY=xxxxxxxx
       - FR24FEED_RECEIVER=beast-tcp
       - FR24FEED_HOST=xx.xx.xx.xx:30005
       - FR24FEED_BS=no
       - FR24FEED_RAW=no
       - FR24FEED_LOGMODE=1
       - FR24FEED_LOGPATH=/tmp
       - FR24FEED_MLAT=yes
       - FR24FEED_MLAT_DASH_WITHOUT_DASH_GPS=yes
       - HTML_FR24_FEEDER_STATUS_PAGE=http://xx.xx.xx.xx:8754/     
       - HTML_RECEIVER_STATS_PAGE_FLIGHTRADAR24=https://www.flightradar24.com/account/feed-stats/?id=T-XXXXXXX
       
####### Planefinder Einstellung ##############     
       - SERVICE_ENABLE_PLANEFINDER=true    
       - PLANEFINDER_SHARECODE=xxxxxxxxxx
    ports:
      - 8754:8754
      - 8080:8080
      - 30053:30053
    logging:
      options:
        max-size: 30m
    tmpfs:
       - /run:exec,size=32M
       - /usr/lib/fr24/public_html/data:size=32M
networks:
  net:
    external:
        name: macvlan

`

## Steps to Reproduce the Problem

  1. restart Container will loss config data for Planefinder 
  1.
  1.

**Comment by Thom-x** [comment]
It is not supported to put a volume on plane finder config file.
If you are using the image as a client. I also do it like that:

```
version: "2"
services:
  fr24feed-piaware:
    restart: unless-stopped
    image: "thomx/fr24feed-piaware:latest"
    devices:
      - "/dev/bus/usb"
    ports:
      - "8754:8754"
    logging:
      options:
        max-size: "30m"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - "DUMP1090_ADDITIONAL_ARGS=--json-location-accuracy 2 --net-bi-port 30004,30104 --net-only"
      - "SERVICE_ENABLE_IMPORT_OVER_NETCAT=true"
      - "DUMP1090_LOCAL_PORT=30004"
      - "DUMP1090_REMOTE_HOST=readsb"
      - "DUMP1090_REMOTE_PORT=30005"
      - "FR24FEED_FR24KEY=xxxxxxx"
      - "PIAWARE_FEEDER_DASH_ID=xxxxxxxx"
      - "SERVICE_ENABLE_ADSBEXCHANGE=true"
      - "ADSBEXCHANGE_UUID=xxxxxxxxxx"
      - "SERVICE_ENABLE_PLANEFINDER=true"
      - "PLANEFINDER_SHARECODE=xxxxxx"
    tmpfs:
      - /run:exec,size=32M
      - /planefinder/log:exec,size=32M
      - /usr/lib/fr24/public_html/data:size=32M
```

Please have a look at https://github.com/Thom-x/docker-fr24feed-piaware-dump1090#dump1090-forwarding
